### ISSUE TITLE
[Issue]: Set Guitar as Keyboard, but PC doesn't detect it

### ISSUE THREAD

**Issue by LilRenlor** [Santroller/Santroller#179]
### Please describe your issue.

I mapped the guitar as keyboard and saved, if I plug the guitar into my Android phone or Chromebook, it works, types the inputs, but on my PC, it doesn't work, no inputs. Is there a specific driver I need to install for it?

### Version

10.1.74

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
what are you trying to play?

**Comment by sanjay900** [comment]
I suspect your using 6KRO, seems thats broken on windows but will be fixed with v10.1.77

If your goal is to play festival, instead of using Keyboard mode you can use normal guitar mode, and just hit `add setting` and add the Festival console mode

doing that will let it emulate a keyboard if you hold a button while plugging the controller in

**Comment by sanjay900** [comment]
10.1.77 is out now
